### PR TITLE
Set profile on all applications and add grails.codegen.defaultPackage

### LINKED ISSUE #374: Grails Forge 7: Error running create-domain-class with no package
**Description**
I can create a domain-calss without being in a package. However grails 7 creates a package named _@artifact.package.path@_ and placess class file in there.  And when i run grails it return error. 

**Steps to Reproduce**
Create a domain-class without package `./grailsw create-domain-class Myemployee`
Then run `./gradlew bootRun`

**Expected Behaviour**
This works in Grails 5 and 6 but not in grails 7

**Actual Behaviour**
it returns error message `/grails-app/domain/@artifact.package.path@/Myemployee.groovy: 1: Unexpected input: '@artifact.package' @ line 1, column 11.`

**Environment Information**
Operating System: Mac OS
Grails Version: 7
JDK Version: 22.0.2

Requires the following in default application.yml:

```
grails:
    codegen:
        defaultPackage: com.example

```

### LINKED ISSUE #384: Problem Creating Artifacts With grailsw
### Expected Behavior

`./grailsw create-service Widget` should create WidgetService in the application's default package.

### Actual Behaviour

`./grailsw create-service Widget` creates the service in an invalid package.

### Steps To Reproduce

Create an application using the Forge UI which includes the Grails Wrapper feature:

Screenshot 2024-10-05 at 7 56 41 AM

In the generated app run `./grailsw create-service ...`

```
$ [] sdk use java 11.0.17-zulu 

Using java version 11.0.17-zulu in this shell.
$ [] 
$ [] 
$ [] git clone git@github.com:osscontributor/grailswdemo.git && cd grailswdemo && ./grailsw create-service Widget
Cloning into 'grailswdemo'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 123 (delta 16), reused 123 (delta 16), pack-reused 0 (from 0)
Receiving objects: 100% (123/123), 783.40 KiB | 2.61 MiB/s, done.
| Resolving Dependencies. Please wait...
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar
> Task :buildSrc:assemble
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build

CONFIGURE SUCCESSFUL in 3s
1 actionable task: 1 executed
| Created grails-app/services/@artifact.package.path@/WidgetService.groovy
| Created src/test/groovy/@artifact.package.path@/WidgetServiceSpec.groovy
$ [main] 
$ [main] 
$ [main] cat grails-app/services/@artifact.package.path@/WidgetService.groovy
@artifact.package@
import grails.gorm.transactions.Transactional

@Transactional
class WidgetService {

    def serviceMethod() {

    }
}

```

### Environment Information

_No response_

### Example Application

https://github.com/osscontributor/grailswdemo

### Version

6.2.1

### PR DESCRIPTION
**Pull request by jamesfredley**
grails-shell requires a profile to run

profiles are mapped 1:1 to the 4 forge application types

profile were being added by the GrailsWrapper feature and they have now been moved over to a new DefaultFeature, GrailsProfiles.

Also adds `grails.codegen.defaultPackage` to `application.yml` which is required by some profile commands

### CODE REVIEW

File: grails-forge-core/src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
+/*
+ * Copyright 2017-2024 original authors
```
Comment (matrei) [inline grails-forge-core/src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java:2]: It's not important and I'm no expert, but shouldn't the year only represent this particular file? So for a new file in 2024, it should only list 2024? Or are there different strategies for this? Please correct me if I'm wrong!

File: grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsProfiles/GrailsProfilesSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+import org.grails.forge.options.Options
+import org.grails.forge.options.TestFramework
+import spock.lang.Unroll
+
+class GrailsProfilesSpec extends ApplicationContextSpec implements CommandOutputFixture {
+
+    @Unroll
+    void "test profile dependency is present for #applicationType application"() {
+        when:
+        def output = generate(applicationType, new Options(TestFramework.SPOCK, JdkVersion.JDK_11))
```
Comment (matrei) [inline grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsProfiles/GrailsProfilesSpec.groovy:17]: Should we hard-code the `JdkVersion` here? If we remove it, it will default to `System.getProperty("java.version")`.

File: grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsProfiles/GrailsProfilesSpec.groovy [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+        def build = output.get("build.gradle")
+        build.contains("profile(\"org.grails.profiles:${applicationType.name.replace("_", "-")}\")")
+
+        where:
+        applicationType << ApplicationType.values().toList()
+    }
+
+    void "test config"() {
+        when:
+        def output = generate(applicationType, new Options(TestFramework.SPOCK, JdkVersion.JDK_11))
```
Comment (matrei) [inline grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsProfiles/GrailsProfilesSpec.groovy:30]: Should we hard-code the `JdkVersion` here? If we remove it, it will default to `System.getProperty("java.version")`.

**Review by matrei — APPROVED** [review]

File: grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsProfiles/GrailsProfilesSpec.groovy (hunk 2 above)
Comment (jamesfredley) [reply grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsProfiles/GrailsProfilesSpec.groovy:17]: I am going to create an issue for this since there are 49 references in this project.

Comment (jamesfredley) [reply grails-forge-core/src/test/groovy/org/grails/forge/feature/grailsProfiles/GrailsProfilesSpec.groovy:17]: https://github.com/grails/grails-forge/issues/390

File: grails-forge-core/src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java (hunk 1 above)
Comment (jamesfredley) [reply grails-forge-core/src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java:2]: Technically 2024 makes the most sense.  Since it was copied and pasted from another feature and only some of it changed, it is possibly a gray area.

I updated to 2024.

Comment (jamesfredley) [reply grails-forge-core/src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java:2]: spotlessJavaCheck would not allow me to change them, so back to 2017-2024.

```
Execution failed for task ':grails-forge-core:spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java
          @@ -1,5 +1,5 @@
           /*
          -·*·Copyright·2024·original·authors
          +·*·Copyright·2017-2024·original·authors
           ·*
           ·*·Licensed·under·the·Apache·License,·Version·2.0·(the·"License");
           ·*·you·may·not·use·this·file·except·in·compliance·with·the·License.
      src/main/java/org/grails/forge/feature/grailsWrapper/GrailsWrapper.java
          @@ -1,5 +1,5 @@
           /*
          -·*·Copyright·2024·original·authors
74 actionable tasks: 39 executed, 26 from cache, 9 up-to-date
          +·*·Copyright·2017-2024·original·authors
           ·*
WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
           ·*·Licensed·under·the·Apache·License,·Version·2.0·(the·"License");
- The deprecated "gradleEnterprise.server" API has been replaced by "develocity.server"
           ·*·you·may·not·use·this·file·except·in·compliance·with·the·License.
- The deprecated "gradleEnterprise.buildScan.publishIfAuthenticated" API has been replaced by "develocity.buildScan.publishing.onlyIf { it.authenticated }"
  Run './gradlew :grails-forge-core:spotlessApply' to fix these violations.
```

Comment (matrei) [reply grails-forge-core/src/main/java/org/grails/forge/feature/grailsProfiles/GrailsProfiles.java:2]: #392

**Comment by codeconsole** [comment]
@jamesfredley does `profile` need to be added back?

```
grails:
  profile: web
```

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-forge/pull/396
